controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - centerbody_to_base_link
      - first_arm_to_centerbody
      - second_arm_to_first_arm
      - end_to_second
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - end_to_second
initial:  # Define initial robot poses per group
  - group: arm
    pose: zero_pos